### PR TITLE
Fix usage of deprecated method of inspect

### PR DESCRIPTION
**Pull request by ArchiDevil**
Hi, I've made change and replaced a deprecated method of `inspect` to a newer one. Nothing functionally changed.

### CODE REVIEW

**Comment by ArchiDevil** [comment]
@kmike, any updates to the PR? It seems like it is failing due to something outdated in testing infrastructure.

**Comment by PalmtopTiger** [comment]
@ArchiDevil, Hi!
use
`args = inspect.getfullargspec(cls.__init__)[0]`
or
`args, *_ = inspect.getfullargspec(cls.__init__)`
instead of multiple _

**Comment by Kowalski0805** [comment]
Hi @ArchiDevil! Could you please make a PR with this fix in [no-plagiarism/pymorphy3 repo](https://github.com/no-plagiarism/pymorphy3)?

**Comment by ArchiDevil** [comment]
Yep, will do it in a couple of hours

чт, 1 дек. 2022 г., 18:47 Illya Fedorovych ***@***.***>:

**Comment by Kowalski0805** [comment]
Hi @ArchiDevil! Any updates on this?

**Comment by ArchiDevil** [comment]
@Kowalski0805, done

https://github.com/no-plagiarism/pymorphy3/pull/7

**Pull request closed without merging**
